// packages/mute8-solid/mute8-solid.ts
import { Store as StoreMute8, StoreDefiniton, ProxyExtension, newStoreProxy } from "../mute8/mute8"
import { createSignal, Accessor, onCleanup, } from 'solid-js';

interface SolidExtension<T> {
    use(): [Accessor<T>, (newValeu: Partial<T>) => void]
    useOne<K extends keyof T>(property: K): [Accessor<T[K]>, (newValue: T[K]) => void]
}

export type Store<T, A, AA> = StoreMute8<T, A, AA> & {
    solid: SolidExtension<T>
}

export const newStore = <T extends Object, A, AA>(store: StoreDefiniton<T, A, AA>) => {
    const reactExtension: ProxyExtension<T, A, AA> = {
        name: "solid",
        init(core) {
            return {
                use() {
                    const [value, setValue] = createSignal(core.s.sanp());
                    const sub = core.s.sub(s => setValue(s as any))
                    onCleanup(() => sub.destroy())
                    return [value, (v: any) => core.s.next(v)]
                },
                useOne(property: keyof T) {
                    const [value, setValue] = createSignal((core.s.sanp() as any)[property]);
                    const sub = core.s.sub((s: any) => setValue(s[property]))
                    onCleanup(() => sub.destroy())
                    return [value, (v: any) => core.update(property, v)]
                }
            }
        },
    }

    return newStoreProxy(store as any, reactExtension) as Store<T, A, AA>
}

export { SubFn, VoidFn, AsyncFn, Sub, Plugin } from "../mute8/mute8"

// packages/mute8-react/mute8-react.ts
import * as mute8 from "../mute8/mute8"
import { Store as StoreMute8, StoreDefiniton, ProxyExtension } from "../mute8/mute8"
import { useState, useEffect } from 'react';

interface ReactExtension<T> {
    use(): [T, (newValeu: Partial<T>) => void]
    useOne<K extends keyof T>(property: K): [T[K], (newValue: T[K]) => void]
}

export type Store<T, A, AA> = StoreMute8<T, A, AA> & {
    react: ReactExtension<T>
}

export const newStore = <T extends Object, A, AA>(store: StoreDefiniton<T, A, AA>) => {
    const reactExtension: ProxyExtension<T, A, AA> = {
        name: "react",
        init(core) {
            return {
                use() {
                    const [value, setValue] = useState(core.s.sanp());
                    useEffect(() => {
                        const sub = core.s.sub((s) => setValue(s))
                        return () => sub.destroy()
                    }, [])

                    return [value, (v: any) => core.s.next(v)]
                },
                useOne(property: keyof T) {
                    const [value, setValue] = useState((core.s.sanp() as any)[property]);
                    useEffect(() => {
                        const sub = core.s.sub((s: any) => setValue(s[property]))
                        return () => sub.destroy()
                    }, [])
                    return [value, (v: any) => core.update(property, v)]
                }
            }
        },
    }

    return mute8.newStoreProxy(store as any, reactExtension) as Store<T, A, AA>
}

export { SubFn, VoidFn, AsyncFn, Sub, Plugin } from "../mute8/mute8"
