// packages/mute8-solid/mute8-solid.ts
import { Store as StoreMute8, StoreDefiniton, ProxyExtension, newStoreProxy } from "../mute8/mute8"
import { createSignal, Accessor, onCleanup, } from 'solid-js';

interface SolidExtension<T> {
    use(): [Accessor<T>, (newValeu: Partial<T>) => void]
    useOne<K extends keyof T>(property: K): [Accessor<T[K]>, (newValue: T[K]) => void]
}

export type Store<T, A, AA> = StoreMute8<T, A, AA> & {
    solid: SolidExtension<T>
}

export const newStore = <T extends Object, A, AA>(store: StoreDefiniton<T, A, AA>) => {
    const reactExtension: ProxyExtension<T, A, AA> = {
        name: "solid",
        init(core) {
            return {
                use() {
                    const [value, setValue] = createSignal(core.s.sanp());
                    const sub = core.s.sub(s => setValue(s as any))
                    onCleanup(() => sub.destroy())
                    return [value, (v: any) => core.s.next(v)]
                },
                useOne(property: keyof T) {
                    const [value, setValue] = createSignal((core.s.sanp() as any)[property]);
                    const sub = core.s.sub((s: any) => setValue(s[property]))
                    onCleanup(() => sub.destroy())
                    return [value, (v: any) => core.update(property, v)]
                }
            }
        },
    }

    return newStoreProxy(store as any, reactExtension) as Store<T, A, AA>
}

export { SubFn, VoidFn, AsyncFn, Sub, Plugin } from "../mute8/mute8"

// _mute8-react/mute8-react.ts
import * as mute8 from "../_mute8/mute8"
import { State as mute8State, StateBuilder, ProxyExtension } from "../_mute8/mute8"
import { useState, useEffect } from 'react';


export type State<T> = mute8State<T> & {
    use(): [T, (newValeu: Partial<T>) => void]
    useOne<K extends keyof T>(property: K): [T[K], (newValue: T[K]) => void]
}

const proxyExtension: <T>() => ProxyExtension<T> = <T>() =>
({
    get(core, prop) {
        if (prop === 'use') {
            const use_fn = () => {
                const [value, setValue] = useState(core.snap());
                useEffect(() => {
                    const sub = core.subscribe((s) => setValue(s))
                    return () => sub.destroy()
                }, [])

                return [value, (v: any) => core.update(v)]
            };

            return {
                value: use_fn
            }
        }

        if (prop === 'useOne') {
            const use_fn = (property: keyof T) => {
                const [value, setValue] = useState((core.snap() as any)[property]);
                useEffect(() => {
                    const sub = core.subscribe((s: any) => setValue(s[property]))
                    return () => sub.destroy()
                }, [])
                return [value, (v: any) => core.updateValue(property, v)]
            };

            return {
                value: use_fn
            }
        }

        return null;
    }
})

export const newState = <T extends Object>(state: StateBuilder<T>) => {
    const core = new mute8.StateCore(state.value);
    const proxy = mute8.proxyBuilder(state.value as any, core, proxyExtension())
    return proxy as State<T>
}
